import { db } from '@/db';
import { jobs } from '@/db/schema';

async function main() {
    const sampleJobs = [
        {
            clientId: 4,
            title: 'Build E-commerce Website',
            description: 'Need a full-stack developer to build a modern e-commerce platform with payment integration',
            budget: 3500,
            deadline: new Date('2024-04-15').toISOString(),
            category: 'Web Development',
            status: 'pending',
            hiredFreelancerId: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            clientId: 5,
            title: 'WordPress Plugin Development',
            description: 'Looking for WordPress expert to create custom plugin for booking system',
            budget: 1200,
            deadline: new Date('2024-03-20').toISOString(),
            category: 'Web Development',
            status: 'in_progress',
            hiredFreelancerId: 14,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            clientId: 6,
            title: 'React Dashboard Application',
            description: 'Build an admin dashboard with React and Node.js backend',
            budget: 2800,
            deadline: new Date('2024-04-30').toISOString(),
            category: 'Web Development',
            status: 'completed',
            hiredFreelancerId: 15,
            createdAt: new Date('2023-12-20').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            clientId: 7,
            title: 'API Integration Project',
            description: 'Need developer to integrate third-party APIs into existing system',
            budget: 900,
            deadline: new Date('2024-03-10').toISOString(),
            category: 'Web Development',
            status: 'in_progress',
            hiredFreelancerId: 16,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            clientId: 8,
            title: 'Website Redesign and Optimization',
            description: 'Redesign existing website with modern UI and improve performance',
            budget: 1500,
            deadline: new Date('2024-04-05').toISOString(),
            category: 'Web Development',
            status: 'pending',
            hiredFreelancerId: null,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            clientId: 9,
            title: 'Design Mobile App UI',
            description: 'Create beautiful UI/UX design for fitness tracking mobile app',
            budget: 800,
            deadline: new Date('2024-03-25').toISOString(),
            category: 'Mobile Apps',
            status: 'completed',
            hiredFreelancerId: 17,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            clientId: 10,
            title: 'iOS App Development',
            description: 'Develop native iOS app for restaurant delivery service',
            budget: 4500,
            deadline: new Date('2024-05-15').toISOString(),
            category: 'Mobile Apps',
            status: 'in_progress',
            hiredFreelancerId: 18,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            clientId: 11,
            title: 'Cross-Platform Mobile App',
            description: 'Build React Native app for social networking',
            budget: 3200,
            deadline: new Date('2024-04-20').toISOString(),
            category: 'Mobile Apps',
            status: 'pending',
            hiredFreelancerId: null,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            clientId: 12,
            title: 'Logo and Brand Identity',
            description: 'Create complete brand identity package including logo, colors, and guidelines',
            budget: 600,
            deadline: new Date('2024-03-15').toISOString(),
            category: 'Design',
            status: 'completed',
            hiredFreelancerId: 19,
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            clientId: 13,
            title: 'UI/UX Design for SaaS',
            description: 'Design user interface for B2B SaaS platform',
            budget: 2000,
            deadline: new Date('2024-04-10').toISOString(),
            category: 'Design',
            status: 'in_progress',
            hiredFreelancerId: 20,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            clientId: 4,
            title: 'Social Media Graphics',
            description: 'Create graphics and templates for social media marketing campaign',
            budget: 350,
            deadline: new Date('2024-03-18').toISOString(),
            category: 'Design',
            status: 'pending',
            hiredFreelancerId: null,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            clientId: 5,
            title: 'Infographic Design',
            description: 'Design professional infographics for business presentation',
            budget: 400,
            deadline: new Date('2024-03-22').toISOString(),
            category: 'Design',
            status: 'completed',
            hiredFreelancerId: 21,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            clientId: 6,
            title: 'Content Writing for Blog',
            description: 'Write 10 SEO-optimized blog posts for tech website',
            budget: 500,
            deadline: new Date('2024-04-01').toISOString(),
            category: 'Writing',
            status: 'in_progress',
            hiredFreelancerId: 22,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            clientId: 7,
            title: 'Technical Documentation',
            description: 'Create comprehensive technical documentation for software product',
            budget: 1000,
            deadline: new Date('2024-04-08').toISOString(),
            category: 'Writing',
            status: 'pending',
            hiredFreelancerId: null,
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },
        {
            clientId: 8,
            title: 'Copywriting for Landing Page',
            description: 'Write compelling copy for product landing pages',
            budget: 450,
            deadline: new Date('2024-03-28').toISOString(),
            category: 'Writing',
            status: 'pending',
            hiredFreelancerId: null,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            clientId: 9,
            title: 'SEO Optimization',
            description: 'Complete SEO audit and optimization for e-commerce website',
            budget: 800,
            deadline: new Date('2024-04-12').toISOString(),
            category: 'Marketing',
            status: 'in_progress',
            hiredFreelancerId: 23,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            clientId: 10,
            title: 'Social Media Management',
            description: 'Manage social media accounts for 3 months with content creation',
            budget: 1800,
            deadline: new Date('2024-05-20').toISOString(),
            category: 'Marketing',
            status: 'in_progress',
            hiredFreelancerId: 24,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            clientId: 11,
            title: 'Email Marketing Campaign',
            description: 'Design and execute email marketing campaign for product launch',
            budget: 650,
            deadline: new Date('2024-03-30').toISOString(),
            category: 'Marketing',
            status: 'pending',
            hiredFreelancerId: null,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            clientId: 12,
            title: 'Data Entry and Cleanup',
            description: 'Clean and organize customer database with 5000+ entries',
            budget: 300,
            deadline: new Date('2024-03-25').toISOString(),
            category: 'Data Entry',
            status: 'completed',
            hiredFreelancerId: 25,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            clientId: 13,
            title: 'Product Catalog Management',
            description: 'Enter and format 500 products into e-commerce platform',
            budget: 400,
            deadline: new Date('2024-04-05').toISOString(),
            category: 'Data Entry',
            status: 'pending',
            hiredFreelancerId: null,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
    ];

    await db.insert(jobs).values(sampleJobs);
    
    console.log('✅ Jobs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});