import { db } from '@/db';
import { profiles } from '@/db/schema';

async function main() {
    const sixMonthsAgo = new Date();
    sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);

    const fiveMonthsAgo = new Date();
    fiveMonthsAgo.setMonth(fiveMonthsAgo.getMonth() - 5);

    const fourMonthsAgo = new Date();
    fourMonthsAgo.setMonth(fourMonthsAgo.getMonth() - 4);

    const sampleProfiles = [
        // 3 Admin Users
        {
            userId: 'admin-uuid-1',
            fullName: 'Admin One',
            email: 'admin1@tasklynk.com',
            role: 'admin',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin1',
            bio: 'Platform administrator with full access',
            skills: null,
            hourlyRate: null,
            createdAt: sixMonthsAgo.toISOString(),
            updatedAt: sixMonthsAgo.toISOString(),
        },
        {
            userId: 'admin-uuid-2',
            fullName: 'Admin Two',
            email: 'admin2@tasklynk.com',
            role: 'admin',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin2',
            bio: 'Platform administrator with full access',
            skills: null,
            hourlyRate: null,
            createdAt: sixMonthsAgo.toISOString(),
            updatedAt: sixMonthsAgo.toISOString(),
        },
        {
            userId: 'admin-uuid-3',
            fullName: 'Admin Three',
            email: 'admin3@tasklynk.com',
            role: 'admin',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin3',
            bio: 'Platform administrator with full access',
            skills: null,
            hourlyRate: null,
            createdAt: sixMonthsAgo.toISOString(),
            updatedAt: sixMonthsAgo.toISOString(),
        },
        // 10 Client Users
        {
            userId: 'client-uuid-1',
            fullName: 'Alice Johnson',
            email: 'client1@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client1',
            bio: 'Startup founder looking for talented freelancers to build innovative solutions',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-2',
            fullName: 'Bob Smith',
            email: 'client2@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client2',
            bio: 'Small business owner seeking creative professionals for marketing projects',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-3',
            fullName: 'Carol Davis',
            email: 'client3@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client3',
            bio: 'Tech company hiring remote workers for ongoing development projects',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-4',
            fullName: 'David Wilson',
            email: 'client4@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client4',
            bio: 'Digital agency looking for specialists in web design and development',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-5',
            fullName: 'Emma Brown',
            email: 'client5@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client5',
            bio: 'E-commerce business owner needing content writers and SEO experts',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-6',
            fullName: 'Frank Miller',
            email: 'client6@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client6',
            bio: 'Marketing consultant seeking data analysts and graphic designers',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-7',
            fullName: 'Grace Lee',
            email: 'client7@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client7',
            bio: 'Product manager looking for mobile app developers and UX designers',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-8',
            fullName: 'Henry Taylor',
            email: 'client8@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client8',
            bio: 'SaaS company founder hiring full-stack developers and DevOps engineers',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-9',
            fullName: 'Ivy Martinez',
            email: 'client9@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client9',
            bio: 'Creative director seeking video editors and motion graphics artists',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'client-uuid-10',
            fullName: 'Jack Anderson',
            email: 'client10@tasklynk.com',
            role: 'client',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=client10',
            bio: 'Real estate company looking for photographers and content creators',
            skills: null,
            hourlyRate: null,
            createdAt: new Date(fiveMonthsAgo.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fiveMonthsAgo.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // 15 Freelancer Users
        {
            userId: 'freelancer-uuid-1',
            fullName: 'Sarah Developer',
            email: 'freelancer1@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer1',
            bio: 'Full-stack JavaScript developer with 5 years of experience building scalable web applications',
            skills: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'TypeScript'],
            hourlyRate: 85,
            createdAt: new Date(fourMonthsAgo.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-2',
            fullName: 'Mike Designer',
            email: 'freelancer2@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer2',
            bio: 'Creative UI/UX designer specializing in modern web and mobile interfaces',
            skills: ['UI/UX Design', 'Figma', 'Adobe XD', 'Sketch', 'Prototyping'],
            hourlyRate: 75,
            createdAt: new Date(fourMonthsAgo.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-3',
            fullName: 'Lisa Writer',
            email: 'freelancer3@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer3',
            bio: 'Professional content writer and copywriter with expertise in SEO and digital marketing',
            skills: ['Content Writing', 'Copywriting', 'SEO', 'Blog Writing', 'Technical Writing'],
            hourlyRate: 50,
            createdAt: new Date(fourMonthsAgo.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-4',
            fullName: 'Tom Marketer',
            email: 'freelancer4@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer4',
            bio: 'Digital marketing specialist with proven track record in SEO and social media campaigns',
            skills: ['SEO', 'Content Marketing', 'Social Media', 'Google Ads', 'Analytics'],
            hourlyRate: 60,
            createdAt: new Date(fourMonthsAgo.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-5',
            fullName: 'Nina Coder',
            email: 'freelancer5@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer5',
            bio: 'Python developer specializing in data analysis, machine learning, and backend development',
            skills: ['Python', 'Data Analysis', 'Machine Learning', 'Django', 'pandas'],
            hourlyRate: 90,
            createdAt: new Date(fourMonthsAgo.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-6',
            fullName: 'Oscar Artist',
            email: 'freelancer6@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer6',
            bio: 'Graphic designer and illustrator creating stunning visuals for brands and businesses',
            skills: ['Graphic Design', 'Illustration', 'Adobe Photoshop', 'Adobe Illustrator', 'Branding'],
            hourlyRate: 70,
            createdAt: new Date(fourMonthsAgo.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-7',
            fullName: 'Paula SEO',
            email: 'freelancer7@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'pending',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer7',
            bio: 'SEO specialist helping businesses rank higher and drive organic traffic',
            skills: ['SEO', 'Keyword Research', 'Link Building', 'Technical SEO', 'Google Analytics'],
            hourlyRate: 55,
            createdAt: new Date(fourMonthsAgo.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-8',
            fullName: 'Quinn Data',
            email: 'freelancer8@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer8',
            bio: 'Data scientist and analyst turning complex data into actionable insights',
            skills: ['Data Science', 'SQL', 'Python', 'Tableau', 'Statistical Analysis'],
            hourlyRate: 100,
            createdAt: new Date(fourMonthsAgo.getTime() + 16 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-9',
            fullName: 'Ryan Mobile',
            email: 'freelancer9@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer9',
            bio: 'Mobile app developer building native iOS and Android applications',
            skills: ['React Native', 'iOS Development', 'Android Development', 'Swift', 'Kotlin'],
            hourlyRate: 110,
            createdAt: new Date(fourMonthsAgo.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-10',
            fullName: 'Sophie Frontend',
            email: 'freelancer10@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer10',
            bio: 'Frontend specialist creating beautiful, responsive user interfaces with modern frameworks',
            skills: ['React', 'Vue.js', 'CSS3', 'HTML5', 'Tailwind CSS', 'Next.js'],
            hourlyRate: 80,
            createdAt: new Date(fourMonthsAgo.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-11',
            fullName: 'Tyler Backend',
            email: 'freelancer11@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'pending',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer11',
            bio: 'Backend engineer specializing in scalable APIs and microservices architecture',
            skills: ['Node.js', 'Express', 'PostgreSQL', 'Docker', 'AWS', 'REST APIs'],
            hourlyRate: 95,
            createdAt: new Date(fourMonthsAgo.getTime() + 22 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-12',
            fullName: 'Uma Fullstack',
            email: 'freelancer12@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'approved',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer12',
            bio: 'Full-stack developer with expertise in both frontend and backend technologies',
            skills: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'PostgreSQL', 'Docker'],
            hourlyRate: 120,
            createdAt: new Date(fourMonthsAgo.getTime() + 24 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 24 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-13',
            fullName: 'Victor UX',
            email: 'freelancer13@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'pending',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer13',
            bio: 'UX researcher and designer focused on creating intuitive user experiences',
            skills: ['UX Research', 'User Testing', 'Wireframing', 'Figma', 'Design Thinking'],
            hourlyRate: 85,
            createdAt: new Date(fourMonthsAgo.getTime() + 26 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 26 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-14',
            fullName: 'Wendy Content',
            email: 'freelancer14@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'pending',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer14',
            bio: 'Content strategist and writer creating engaging content for digital platforms',
            skills: ['Content Strategy', 'Copywriting', 'Blog Writing', 'Social Media Content', 'Email Marketing'],
            hourlyRate: 45,
            createdAt: new Date(fourMonthsAgo.getTime() + 28 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'freelancer-uuid-15',
            fullName: 'Xavier Video',
            email: 'freelancer15@tasklynk.com',
            role: 'freelancer',
            accountStatus: 'pending',
            profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=freelancer15',
            bio: 'Video editor and motion graphics artist creating professional video content',
            skills: ['Video Editing', 'Adobe Premiere', 'After Effects', 'Motion Graphics', 'Color Grading'],
            hourlyRate: 70,
            createdAt: new Date(fourMonthsAgo.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(fourMonthsAgo.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(profiles).values(sampleProfiles);
    
    console.log('✅ Profiles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});